main_text = [['Association', " APURE a pour objet la recherche, le développement, la promotion et la mise en oeuvre de solutions tendant à assurer, au juste coût et dans le respect de l'environnement, la valorisation des pneumatiques usagés"], 
['Bactérie', ' Une Bactérie est un organisme microscopique unicellulaire, du grec baktéria ou bâton, de forme shérique (cocci), allongée(bacilles) ou spiralée, ne possédant pas de membrane nucléaire, se nourrissant de diverses façons et se multipliant par divisions successives'], 
['Biodiversité', ' La biodiversité est un terme qui désigne la diversité du monde vivant à tous les niveaux '], 
['Biotope', " Un biotope désigne une aire géographique caractérisée par des conditions climatiques et physicochimiques homogènes permettant l'existence d'une faune et d'une flore spécifiques"], 
['Bordereau', ' L arrêté du 4 janvier 1985 relatif au contrôle des circuits d élimination de déchets générateurs de nuisances institue un bordereau de suivi (BSDI)'], 
['Boue', " Résidus obtenus après traitement d'effluents"], 
['Centrale', ' Centrale de production d électricité à partir de l énergie des marées (des turboalternateurs sont mis en mouvement par chaque marée montante et descendante qui remplit ou vide une retenue d eau)'], 
['Charbon', ' Terme générique qui désigne un ensemble de combustibles solides de compositions et de pouvoir calorifiques très variés'], 
['Chaufferie', " Désigne un local qui accueille un ou plusieurs générateurs destinés à assurer une production collective de chauffage et d'eau chaude sanitaire"], 
['Combustibles', ' les combustibles minéraux solides comprenent '], 
['Compétition', " Désigne en écologie, l interaction des organismes vivants, pour l'accaparement des ressources limitées d'un milieu donné, et qui entraîne, le plus souvent, la domination d'un individu ou d'un groupe d'individus, d'une espèce ou d'un groupe d'espèces"], 
['Compostage', ' Le compostage désigne un procédé de traitement biologique aérobie de matières fermentescibles dans des conditions contrôlées'], 
['Débit', " Débit moyen le plus bas d'un cours d'eau"], 
['Déchet', ' Un déchet industriel banal (DIB) est un déchet ni inerte ni dangereux, généré par les entreprises dont le traitement peut éventuellement être réalisé dans les mêmes installations que les ordures ménagères '], 
['Déclaration', " 27 principes de développement durable constituent la Déclaration de Rio, adoptée à l'unanimité par 178 Etats en juin 1992"], 
['Décomposeur', ' Désigne un organisme hétérotrophe décomposant la matière organique morte (cadavres, végétaux morts, '], 
['Dépôt', ' Dépôt illicite et incontrôlé de déchets'], 
['Développement', ' Le développement durable, est une notion récente qui désigne des actions visant à concilier trois mondes différents, celui de l économie, celui de l écologie et celui du social'], 
['Directive', ' Directive CEE faisant suite à la catastrophe de SEVESO en Italie'], 
['Eau', " L'Eau de process désigne l'eau utilisée dans les installations industrielles pour le fonctionnement d'un procédé ou la fabrication d'un produit"], 
['Éco-Emballages', " Eco-Emballages est une entreprise privée, agréée le 12 Novembre 1992 par l'Etat, qui collecte une somme de 1 à 3 centimes par emballage produit par les entreprises (80 milliards d'emballages ménagers concernés en 1992, ce qui représentent la moitié du volume et le tiers du poids des déchets ménagers)"], 
['Écocitoyen', " Écocitoyen est un concept relatif à un Homme qui a intégré la nécessité de protéger l'environnement dans sa vie quotidienne"], 
['Écologie', " Terme provenant du grec ''Oikos'' et qui signifie maison (sciences de l'habitat) et logos qui signifie discours"], 
['Écosystème', " Un écosystème est un système au sein duquel il existe des échanges cycliques de matières et d'énergie, dus aux interactions entre les différents organismes présents (biocénose) et leur environnement (biotope)"], 
['Effet', " L effet de serre est un phénomène d'échauffement de la surface de la Terre et des couches basses de l'atmosphère."], 
['Effluent', ' Terme générique désignant une eau résiduaire urbaine ou industrielle, et plus généralement tout rejet liquide véhiculant une certaine charge polluante (dissoute, colloïdale ou particulaire)'], 
['Energie', " L'énergie marémotrice désigne l'énergie provenant des phénomènes des marées"], 
['Étude', " Une étude d'impact sur l'environnement (EIE), ou étude d'incidences sur l'environnement (EIE), est une étude préalable à la mise en cuvre de programmes ou de plans et à la réalisation d'équipements, qui permet d'estimer leurs effets probables sur l'environnement"],
['Fiche', " Désigne les documents techniques indiquant les effets possibles sur la santé de l'exposition à un produit, la manière de protéger les travailleurs, l'évaluation des risques relatifs à l'utilisation, à l'entreposage et à la manipulation du produit ainsi que les mesures d'urgence"]]